### ISSUE TITLE
Xperia 5 j9210 only 1SIM available.

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/droid-hal-version-sony-kumano#1]
I flashed Sailfish_OS-Sailfish-SonyXperia-4.4.0.68-j9210-1.0.0.6.zip. Only 1SIM available.

**Comment by Thaodan** [comment]
Please open an issue here:
https://github.com/SailfishOS-SonyXperia/bugs/issues/new/choose

**Comment by VZuyev** [comment]
Xperia 10 II 2SIM work.
