### ISSUE TITLE
Scale on Xperia 5

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/droid-hal-version-sony-kumano#3]
Everything is a bit bigger than the Xperia 10 II comparison. Favorite contacts are displayed in two columns (in 10II favorite contacts are displayed in three columns).

**Comment by Thaodan** [comment]
Please open an issue here: [SailfishOS-SonyXperia/bugs](https://github.com/SailfishOS-SonyXperia/bugs/issues/new/choose).
